### ISSUE TITLE
p1203Pq warning when using multiple stall events

### ISSUE THREAD

**Issue by jq5** [itu-p1203/itu-p1203#12]
Hi all,

I have a json file (outlined below), with 2 segments and 2 stalls.

When I run it with "python3 -m itu_p1203 <file.json>", I get:
WARNING - p1203Pq - Excluding stalling event at position 10, since it is outside of media range

Am I setting the stalls incorrectly?

I did notice in your code (p1203Pq.py):

line 57: max_dur = min(len(O21), len(O22))

this always sets max_dur to zero, as I don't have audio in my files

should this be, using max and not min, i.e.

max_dur = max(len(O21), len(O22))

anyway, thanks for the help,

J

```
{
    "I11": {
        "segments": [],
        "streamId": 42
    },
    "I13": {
        "segments": [
            {
                "bitrate": 289.83,
                "codec": "h264",
                "duration": 10.0,
                "fps": 24.0,
                "resolution": "320x180",
                "start": 0
            },
            {
                "bitrate": 3588.96,
                "codec": "h264",
                "duration": 10.0,
                "fps": 24.0,
                "resolution": "320x180",
                "start": 10.0
            }
        ],
        "streamId": 42
    },
    "I23": {
        "stalling": [[0,1],[10,11]],
        "streamId": 42
    }, 
    "IGen": {
        "device": "pc",
        "displaySize": "1920x1080",
        "viewingDistance": "150cm"
    }
}
```

**Comment by slhck** [comment]
You have no audio, and indeed, the algorithm expects there to be an audio stream that's as long as the video stream. You could try adding a dummy audio sequence:

```
{
    "I11": {
        "segments": [
            { "bitrate": 192, "codec": "aac", "duration": 20, "start": 0 }
        ],
        "streamId": 42
    },
    "I13": {
        "segments": [
            {
                "bitrate": 289.83,
                "codec": "h264",
                "duration": 10.0,
                "fps": 24.0,
                "resolution": "320x180",
                "start": 0
            },
            {
                "bitrate": 3588.96,
                "codec": "h264",
                "duration": 10.0,
                "fps": 24.0,
                "resolution": "320x180",
                "start": 10.0
            }
        ],
        "streamId": 42
    },
    "I23": {
        "stalling": [[0,1],[10,11]],
        "streamId": 42
    },
    "IGen": {
        "device": "pc",
        "displaySize": "1920x1080",
        "viewingDistance": "150cm"
    }
}
```

The standard itself does not specify what should be done if there's no audio, so a constant good audio quality stream will be assumed. But in the case where the user does not specify *any* audio, the file should not be truncated like this. I'll investigate.

**Comment by jq5** [comment]
Cool, but on the GitHub main page, you have:
> The input JSON file (see files in examples) must have at least the following data: (which is I13 video)
With the other keys and data being optional...

I have another question :)
When I run my json file above, but with only one stall in the first segment
> "stalling": [[0,1]],"
the output for "022" is as per the following (same structure for "034"):

```
"O22": [
   1.05,
   1.05,
   1.05,
   1.05,
   1.05,
   1.05,
   1.05,
   1.05,
   1.05,
   1.063571507795132,
   1.063571507795132,
   1.063571507795132,
   1.063571507795132,
   1.063571507795132,
   1.063571507795132,
   1.063571507795132,
   1.063571507795132,
   1.063571507795132,
   1.063571507795132,
   1.063571507795132
  ],
```
I get 9 values for the first 10 second segment, and 11 values for the second 10 second segment.

I can understand why you reduce the values for the first segment by one second as it stalled for that duration, but why is there an additional value in the second segment, as it did not play for 11 seconds.

Thanks for the help,

J

**Comment by slhck** [comment]
> The input JSON file (see files in examples) must have at least the following data: (which is I13 video)
With the other keys and data being optional...

That's true. We should add some "fake" audio if there is nothing specified, and only truncate to `min` if the user *did* specify a real, shorter audio stream.

About your other question: note that the segments are purely virtual. You get 20 output values for 20 seconds worth of video. If the quality does not change between those two segments, they are treated as one big segment. The stalling is not factored in at all in the calculation of O22. The change in values you see is due to a “sliding window” implemented in the O22 calculation (class `MeasurementWindow`).

**Comment by slhck** [comment]
I should add that the quality stays extremely low because these are low resolution segments, and no bitrate improvement is going to make the overall quality better.

**Comment by jq5** [comment]
I appreciate the values are low, I just want to make sure I'm understanding the input json file properly :)

I see the output I get is just a warning, I assume it does not make a difference to the output value?

or should I add the fake audio to the json file?

I assume the stalling is factorised into the 034 calculation.

Thank you for all your help with this,

Best wishes,

J

**Comment by jq5** [comment]
One other query:
You mention sliding window above.  I think I remember 10 seconds being mentioned somewhere.

So say I have 10 number 10-second segments, and I want to determine the P.1203 value when each one is added to the play buffer.

So when segment 1 is added I calculate P.1203 on it, for segment 2, I calculate over segment 1 and segment 2, and on...

do I repeat this until for segment 10, I calculate P.1203 over the previous 10 segment (100 seconds) or just I just calculate over _n_ segments based on _m_ seconds of content.

Cheers,

J

**Comment by slhck** [comment]
> I see the output I get is just a warning, I assume it does not make a difference to the output value?

It will make a difference!

> or should I add the fake audio to the json file?

Yes, that would be the best workaround until we can implement proper handling of missing audio.

> I assume the stalling is factorised into the 034 calculation.

No. This is just per-second audiovisual quality.

> So say I have 10 number 10-second segments, and I want to determine the P.1203 value when each one is added to the play buffer. So when segment 1 is added I calculate P.1203 on it, for segment 2, I calculate over segment 1 and segment 2, and on... do I repeat this until for segment 10, I calculate P.1203 over the previous 10 segment (100 seconds) or just I just calculate over n segments based on m seconds of content.

If you really need the quality at any point in time where a segment is added, what I would recommend is calculating the *entire* P.1203 quality cumulatively until the current point in time, using all segments. This way the measurement window will be used correctly.

An alternative will be to not use the measurement window at all and just calculate one MOS value for each segment, repeat these values on a per-second basis for the entire length of the segment, and then construct the O.22 input from that. This, however, will mean the measurement window is not used in a standards-conform manner.

**Comment by jq5** [comment]
Perfect, thank you for all your help,

Best wishes,

J
