### ISSUE TITLE
Audio-only quality measure

### ISSUE THREAD

**Issue by daridar** [itu-p1203/itu-p1203#20]
Hey!

Thank you for such a great implementation.
It works great on mp4 files. 
Is it possible to get it to work on wav/mp3 data? To calculate audio quality? 

Thank you.

**Comment by slhck** [comment]
Unfortunately it is not valid to use this model for audio only. In principle you can use the `P1203Pa` class to calculate an audio-only quality score for every second of audio based on codec and bitrate, but the performance of this model (i.e. its accuracy with respect to human ratings) has not been validated.

One ITU-T standard for calculating audio quality would be ITU-R BS.1387; most other ITU standards focus on speech quality only, like ITU-T P.862 (PESQ) or P.863 (POLQA)-

**Comment by daridar** [comment]
Hello!

Thank you for your answer!
Unfortunately, most of these measures from ITU-T require 2 samples (initial and distorted). 
I have only 1 sample - it's audio call, don't you know some measures which could be applicable for my situation? 
I've found only this library: https://github.com/aliutkus/speechmetrics 
Here 2 metics are available for absolute audio quality measurement, but they are not like traditional (certified) MOS values for audio, so I think it's not fair enough to use these values as a MOS approximation. 

If you have any comments on this, I would be happy to get them. 
Thank you so much.

**Comment by slhck** [comment]
You're right, these models are full-reference and require both input and output samples.

Also relevant might be: https://github.com/google/visqol

The repository you found actually seems very promising. But as you said, these models have not been standardized. Then again, there are no standards for no-reference (i.e. distorted sample only) models for speech or audio, as far as I know.
