### ISSUE TITLE
Q: p1203.3 video only quality measure 

### ISSUE THREAD

**Issue by gdavila** [itu-p1203/itu-p1203#24]
p1203.3 could be used to measure visual/video quality only? Specifically, I want to understand if it is comparable with full reference metrics such as VMAF and PSNR (for HD/AVC only) . I thought it was when used in bitstream mode, however the table 3 - ITU-T P-1203 mentions that the model is not intented to :

> Direct comparison/benchmarking of encoder implementations, and thus of services that employ different
encoder implementations

Any thoughts are welcome.

**Comment by slhck** [comment]
You may want to read [our technical report](https://telecommunication-telemedia-assessment.github.io/bitstream_based_models/documents/tech-report-bitstream-based-models.pdf), in particular about the different model types. PSNR/SSIM/VMAF etc. are full-refererence pixel-based models and are *somewhat* codec-agnostic*, whereas bitstream-based models like P.1203.1 (the part that is responsible for the O.22 "Pv" video MOS scores) are more specific to certain codecs/encoders.

I assume by "P.1203.3" in your original post you meant P.1203.1 Mode 3 (bitstream)? Now I think that you could still use P.1203.1 Mode 3 to compare the output from different encoders, as the used features are pretty standard (QP values, basically) and there are no fancy functions or a likelihood of overfitting, but really you want to use a FR model for such tasks, as those can pick up more minuscule differences in quality.

*This doesn't mean you can safely use VMAF for new codecs with e.g. new artifacts that the model has not seen during its training phase.

**Comment by gdavila** [comment]
Thanks and yes, I was talking about P.1203.1 Mode 3, sorry my misunderstanding. 

The technical report is exactly what  I was looking for. I have in mind to do some high level tests on ITU P1203.1 mode 3 vs VMAF for different encoders to better understand how reliable are QP values.

**Comment by slhck** [comment]
You're welcome. I'd be very interested to hear about your findings.

Node that the quality calculations of P.1203.1 has been somewhat reverse-engineered from up to 5-minute video clips, so they might not be as fine-grained as those stemming from a video model trained on short sequences.

In your comparisons, you may want to try [P.1204.3](https://github.com/Telecommunication-Telemedia-Assessment/bitstream_mode3_p1204_3) instead, which is the one we also describe in the technical report.

**Comment by gdavila** [comment]
[here](https://gdavila.github.io/broadcast/vmaf_vs_p1203/2020-10-07-vmaf_vs_p1203/) some empirical results for vmaf vs P.1203.1 if you wan to take a look.

Regarding the P.1204.3, it's not clear to me if it works with HD (1080p) videos or not. It seems that the model supports UHD/4K only. Am I missing something?

**Comment by slhck** [comment]
Very interesting, thanks!

About P.1204.3, you can use it with any input video resolution, however it will be assumed that the video will be displayed on a UHD-1/4K monitor. So it's comparable to what the VMAF 4K model assumes. It means that you will get lower video quality scores due to the assumed reduction of spatial quality due to upscaling by the display.
