### ISSUE TITLE
Question on Stalling Events

### ISSUE THREAD

**Issue by tbabak** [itu-p1203/itu-p1203#25]
Hello, I do have questions on how to calculate the results for a streaming session including stalling events;

In my work, I'm stitching the segments of a streamed video session together.
Thanks to the good README file, I know how to define those events, simply by adding a new entry like `[stalling-start-timestamp, stalling-duration]` to the input json which i'm preparing to pass to the model.

The questions are:
- First, Should I inject a "fake stalling video" of the same `stalling-duration` in between the stitched segments on the times defined as `stalling-start-timestamp` or those defined periods will be somehow added to the media as a "stalling event"?
- Secondly, if I need to inject those "fake stalling videos", are those defined stalling periods being ignored in terms of "video quality" in the final `O34` and `O46` score calculations?

Many thanks for the good work.

**Comment by slhck** [comment]
> Should I inject a "fake stalling video" of the same stalling-duration

No, you don't have to. The media timeline is created based on the segments, and the stalling events are spliced in automatically. You can imagine the model first looking at video only, audio only, and only then taking into account the stalling later on.

Hence, your second question is not relevant for this case.

I hope this clarifies your issue!

**Comment by tbabak** [comment]
Thank you @slhck for the clear clarification.
