### ISSUE TITLE
The examples does not seems to be running anymore. 

### ISSUE THREAD

**Issue by plebreton** [itu-p1203/itu-p1203#27]
Hello,

With the latest version, it seems that the usage examples do not run anymore.

`p1203-standalone -m 0 examples/mode0.json`

Will results in this error on my machine (Ubuntu)

`Traceback (most recent call last):
  File "/home/.../.local/bin/p1203-standalone", line 7, in <module>
    from itu_p1203.__main__ import main
  File "/home/.../.local/lib/python3.6/site-packages/itu_p1203/__init__.py", line 3, in <module>
    from itu_p1203.p1203Pa import P1203Pa
  File "/home/.../.local/lib/python3.6/site-packages/itu_p1203/p1203Pa.py", line 37, in <module>
    class P1203Pa(object):
  File "/home/.../.local/lib/python3.6/site-packages/itu_p1203/p1203Pa.py", line 44, in P1203Pa
    @lru_cache
  File "/usr/lib/python3.6/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None`

From reading the error message, it seems that it is related to the use of non-integer duration. 

Just, FYI, I had an old version on my machine (1.2.8) which runs fine.

**Comment by slhck** [comment]
It works for me under macOS (Python 3.8), but I made a slight fix based on [this Q&A](https://stackoverflow.com/questions/47218313/use-functools-lru-cache-without-specifying-maxsize-parameter). Please let me know whether that works!

**Comment by slhck** [comment]
See 5853897ec7e2ce460eb47e3fe494cfdab5e7386a

**Comment by plebreton** [comment]
Thanks that fixed it!

Yeah, that computer is running an ubuntu LTS, so the python version is a bit old... 
Anyway, now it works, thanks !
