### ISSUE TITLE
Can i use this implementation for .ts (transport stream) files?

### ISSUE THREAD

**Issue by F4RAN** [itu-p1203/itu-p1203#33]
## code changes
change `valid_video_exts` in `__main__.py`

    valid_video_exts = ["avi", "mp4", "mkv", "nut", "mpeg", "mpg"]

to

    valid_video_exts = ["avi", "mp4", "mkv", "nut", "mpeg", "mpg", "ts"]

<hr>

in `extractor.py` in `get_stream_size()` function change
    
    size = sum([l for l in stdout.split("\n") if l != ""])

to
    
    size = 0
    for l in stdout.split("\n"):
        if l != "":
            if l.find("|"):
                l = l.split("|")[0]
                size += int(l)
## question
I do this changes in your code and it accepts ".ts" inputs now,
do you think the results are valid?

**Comment by slhck** [comment]
Your code was almost working, but it would have broken compatibility with other extensions (your `if l.find(…)` had no matching `else`).

Fixed in the most recent version.

Note that MPEG-2 codecs are not supported by P.1203.1 — your TS files need to contain MPEG-4 Part 10 (AVC) video.

**Comment by slhck** [comment]
It would only be valid if you remuxed the file, that is, not re-encoding it. For instance:

    ffmpeg -i input.ts -c copy output.mp4

But it's very likely the Transport Stream file uses an unsupported codec.
