### ISSUE TITLE
Question: would it work with newer numpy?

### ISSUE THREAD

**Issue by sznadas** [itu-p1203/itu-p1203#38]
Hi,

Any chance this is working with a newer/ the newest numpy? Want to use a newer numpy, but this locks my scripts to an older version.

Szilveszter

**Comment by slhck** [comment]
Welcome to Python dependency resolution hell! There seems to be no happy path for including recent numpy _and_ keeping backwards-compatibility with all supported Python versions.
(Latest Numpy is only compatible with Python 3.10 and higher, while 3.8 is just going out of its support lifecycle.)

I'll see if I can upgrade to something newer. Which version are you using?
Are you using poetry as well, or just plain pip?

**Comment by slhck** [comment]
Can you check if 1e521518d3eb7211cce4528f1584d24929798780 is sufficient for you?

**Comment by sznadas** [comment]
Thanks :)

Pip only. Had some issue with pickle an numpy when a pickle was generated on a machine with numpy 2.1 and my numpy was old because of this dependency. Solved it though, a newer 1.x was working well with 2, and I do not actually need the numpy features.

The update you made works well. Thanks!

**Comment by slhck** [comment]
Glad we could solve it!

Yeah, numpy has a compatibility change with pkl files that they backported to some 1.x version. I generally avoid pkl files altogether, because they're not stable enough, but I realize there are some use cases where no simple alternatives exist.
