### ISSUE TITLE
Output is not one score per second

### ISSUE THREAD

**Issue by pedosb** [itu-p1203/itu-p1203#7]
Hello,

The documentation specifies that the code would output one MOS per second, so I was expecting the snippet below to output two scores, but it is outputting 4, am I doing or interpreting something wrong?

```python
from itu_p1203 import P1203Standalone
itu_input = \
{'I13': {'segments': [{'bitrate': 103423.0,
                       'codec': 'h264',
                       'duration': 2,
                       'fps': 30.0,
                       'representation': 1,
                       'resolution': '256x144',
                       'start': 0}],
         'streamId': 1},
 'IGen': {'device': 'pc', 'displaySize': '3840x2160', 'viewingDistance': 10}}
itu_p1203 = P1203Standalone(itu_input)
print(itu_p1203.calculate_pv())
```

Output: `{'video': {'streamId': 1, 'mode': 0, 'O22': [1.05, 1.05, 1.05, 1.05]}}`

Thank you for sharing your project!

**Comment by slhck** [comment]
Thanks for observing this bug! The respective function was missing a return statement, so it added the score twice. It's fixed in `v1.2.3` now.
