### ISSUE TITLE
Stalling input information

### ISSUE THREAD

**Issue by AnatoliyZabrovskiy** [itu-p1203/itu-p1203#8]
Hello!

Thanks for this software. 
Can you explain how to add stalling events in json input file. When I define stalling event(s) like this: "stalling": [20.078, 1],
I get the following error:
ERROR - __main__ - Error during processing, existing: 'float' object is not subscriptable

What is wrong here?

{
    "I11": {
        "segments": [
            {
                "bitrate": 331.46,
                "codec": "aac",
                "duration": 5.48,
                "start": 0
            },
            {
                "bitrate": 333.02,
                "codec": "aac",
                "duration": 5.0,
                "start": 5.48
            },
            {
                "bitrate": 333.2,
                "codec": "aac",
                "duration": 5.0,
                "start": 10.48
            },
            {
                "bitrate": 333.57,
                "codec": "aac",
                "duration": 4.598,
                "start": 15.48
            }
        ],
        "streamId": 42
    },
    "I13": {
        "segments": [
            {
                "bitrate": 691.72,
                "codec": "h264",
                "duration": 5.48,
                "fps": 25.0,
                "resolution": "1920x1080",
                "start": 0
            },
            {
                "bitrate": 4158.04,
                "codec": "h264",
                "duration": 5.0,
                "fps": 25.0,
                "resolution": "1920x1080",
                "start": 5.48
            },
            {
                "bitrate": 7172.66,
                "codec": "h264",
                "duration": 5.0,
                "fps": 25.0,
                "resolution": "1920x1080",
                "start": 10.48
            },
            {
                "bitrate": 6593.59,
                "codec": "h264",
                "duration": 4.598,
                "fps": 25.0,
                "resolution": "1920x1080",
                "start": 15.48
            }
        ],
        "streamId": 42
    },
    "I23": {
        "stalling": [20.078, 1],
        "streamId": 42
    },
    "IGen": {
        "device": "pc",
        "displaySize": "1920x1080",
        "viewingDistance": "150cm"
    }
}

**Comment by slhck** [comment]
Stalling information has to be a list of lists, with one entry per stalling:

```
    "stalling": [
      # pair of `[start timestamp, duration]` for each stalling event
      # where the start timestamp is measured in media time
    ]
```

So in your case, simply wrap it in another bracket:

```
[[20.078, 1]]
```

**Comment by AnatoliyZabrovskiy** [comment]
Thank you! 
And how can I define/add a video startup time? Is this a stalling event ("stalling": [....) too?

**Comment by slhck** [comment]
Yes, this will be the first stalling event, and it should start at position 0.
